# azure-pipelines.yml
# Pipeline to mirror Azure DevOps repository to GitHub

trigger:
  branches:
    include:
    - main
    - master
    # Add other branches you want to trigger the mirroring

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0  # This ensures all history is fetched

- task: Bash@3
  displayName: 'Mirror to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      # Configure Git identity for the pipeline
      git config --global user.name "matthewnewboult"
      git config --global user.email "matthew.newboult@theaccessgroup.com"
      
      # Add GitHub as a remote repository
      git remote add github https://$(githubPat)@github.com/adambrayaccess/accept-reject-referral-13.git
      
      # Push all branches and history to GitHub
      git push --force github --all
      
      # Push all tags to GitHub
      git push --force github --tags
  env:
    githubPat: $(githubPat)

schedules:
- cron: "0 */6 * * *"  # Run every 6 hours (optional)
  displayName: Scheduled mirror
  branches:
    include:
    - main
  always: true