# azure-pipelines.yml
# Pipeline to mirror Azure DevOps repository to GitHub

trigger:
  branches:
    include:
    - main
    - master
    # Add other branches you want to trigger the mirroring

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0  # This ensures all history is fetched

- task: Bash@3
  displayName: 'Mirror to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      # Configure Git identity for the pipeline
      git config --global user.name "matthewnewboult"
      git config --global user.email "matthew.newboult@theaccessgroup.com"

      echo "Current branch and commit information:"
      git branch
      git rev-parse HEAD
      echo "Last 5 commits:"
      git log -n 5 --oneline
      
      # Add GitHub as a remote repository
      echo "Configuring GitHub remote..."
      git remote remove github 2>/dev/null || true
      git remote add github https://$(githubPat)@github.com/adambrayaccess/accept-reject-referral-13.git

      echo "List of remotes:"
      git remote -v
      
      echo "Fetching from GitHub to compare..."
      git fetch github
      
      echo "Comparing branches with GitHub:"
      git rev-list --left-right --count origin/main...github/main || echo "Unable to compare, continuing"
      
      echo "Forcing push to GitHub regardless of status:"
      git push --force github HEAD:main
      git push --force github --tags
  env:
    githubPat: $(githubPat)

schedules:
- cron: "0 */6 * * *"  # Run every 6 hours (optional)
  displayName: Scheduled mirror
  branches:
    include:
    - main
  always: true