name: Mirror to Azure DevOps

on:
  push:
    branches: [ main ] # Adjust branch names as needed

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Mirror to Azure DevOps
      run: |
        git remote add ado https://${{ secrets.ADO_PAT }}@dev.azure.com/access-devops/Access%20HSC%20-%20Shared%20Micro%20Services/_git/ReferralLovableMirror
        git push ado --mirror

        
